In [1]:
%matplotlib inline               
import pandas as pd              # A beautiful library to help us work with data as tables
import numpy as np               # So we can use number matrices. Both pandas and TensorFlow need it. 
import matplotlib.pyplot as plt  # Visualize the things
import tensorflow as tf          # Fire from the gods

In [2]:
dataframe = pd.read_csv("data.csv") # Let's have Pandas load our dataset as a dataframe
dataframe = dataframe.drop(["index", "price", "sq_price"], axis=1) # Remove columns we don't care about
dataframe = dataframe[0:10] # We'll only use the first 10 rows of the dataset in this example
dataframe # Let's have the notebook show us how the dataframe looks now

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [4]:
dataframe.loc[:, ("y1")] = [1, 1, 1, 0, 0, 1, 0, 1, 1, 1] # This is our friend's list of which houses she liked
                                                          # 1 = good, 0 = bad
dataframe.loc[:, ("y2")] = dataframe["y1"] == 0           # y2 is the negation of y1
dataframe.loc[:, ("y2")] = dataframe["y2"].astype(int) 
dataframe

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   1   0
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   0   1
7  1427.0        3.0   1   0
8  1380.0        3.0   1   0
9  1494.0        3.0   1   0

In [5]:
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
inputY = dataframe.loc[:, ["y1", "y2"]].as_matrix()

# .loc enables slicing as in numpy

In [7]:
inputX1 = dataframe[['area', 'bathrooms']].as_matrix()
inputY1 = dataframe[["y1", "y2"]].as_matrix()

In [8]:
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [9]:
inputX1

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [14]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [15]:
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [18]:
X = tf.placeholder(tf.float32,[None,2])
W = tf.Variable(tf.zeros([2,2]))
b = tf.Variable(tf.zeros([2]))
y_values = tf.add(tf.matmul(X,W),b)
y = tf.nn.softmax(y_values)
y_ = tf.placeholder(tf.float32,[None,2])

In [19]:
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [20]:
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [21]:
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={X:inputX, y_:inputY})
    
    if i % display_step == 0 :
        temp = sess.run(cost, feed_dict={X:inputX, y_:inputY})
        print("training_cost",temp)
        
print("training completed")
print(sess.run(cost,feed_dict={X:inputX, y_:inputY}))

training_cost 0.114959
training_cost 0.10954
training_cost 0.10954
training_cost 0.10954
training_cost 0.10954
training_cost 0.10954
training_cost 0.10954
training_cost 0.10954
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109539
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109538
training_cost 0.109537
training_cost 0.109537
training_cost 0.109537
training completed
0.109537


In [22]:
print("optimized_Values", "W=", sess.run(W), "b=", sess.run(b))

optimized_Values W= [[  2.14149564e-04  -2.14149914e-04]
 [  5.12748193e-05  -5.12747974e-05]] b= [  1.19155184e-05  -1.19155284e-05]


In [24]:
sess.run(y, feed_dict={X: inputX })

array([[ 0.71125221,  0.28874779],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718789,  0.35281211],
       [ 0.78335613,  0.2166439 ],
       [ 0.70069474,  0.29930523],
       [ 0.65866327,  0.34133676],
       [ 0.64828628,  0.35171372],
       [ 0.64368278,  0.35631716],
       [ 0.65480113,  0.3451989 ]], dtype=float32)

In [25]:
sess.run(tf.nn.softmax([1., 2.]))

array([ 0.26894143,  0.7310586 ], dtype=float32)